<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EDAL3S7" failures="2" tests="12" name="PetstoreTest" time="23.56" errors="0" timestamp="2025-04-22T11:56:47 IST">
  <testcase classname="api.test.UserTest" name="testPostUser" time="5.515"/>
  <testcase classname="api.test.UserTest" name="testReadUser" time="1.423"/>
  <testcase classname="api.test.UserTest" name="testUpdateUser" time="1.412"/>
  <testcase classname="api.test.UserTest" name="testDeleteUser" time="1.387"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.419"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.422"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.39"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.414"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="1.484"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="1.452">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUser(DataDrivenTests.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="1.388">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUser(DataDrivenTests.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="1.405"/>
</testsuite> <!-- PetstoreTest -->
